#!/bin/bash
#PBS -l nodes=1:ppn=96
#PBS -N rec_concatmwpm
#PBS -o /home/u592165f/workplace/concatenated-decoder/cluster/outputs/out
#PBS -e /home/u592165f/workplace/concatenated-decoder/cluster/outputs/err
ulimit -s unlimited
set -euo pipefail

source ~/anaconda3/etc/profile.d/conda.sh
conda activate concat_decoder

cd "$PBS_O_WORKDIR"

CONFIG="configs/cluster_memory_simulation.json"
SHOTS=""
BATCH=""
WORKERS="96"
QUIET="quiet"

bash scripts/run_memoryexp.sh "$CONFIG" "$SHOTS" "$BATCH" "$WORKERS" "$QUIET"
