"""concat-decoder — Concatenated color-code decoder library.

Public decoders
---------------
ConcatMWPMDecoder
    Concatenated MWPM decoder (pure graph-based, two-stage).
ConcatBPMatchingDecoder
    Hybrid BP→MWPM decoder (belief propagation stage 1, MWPM stage 2).

Both decoders take a `stim.Circuit` as input (generated by chromobius or
color-code-stim) and expose a `decode_batch(detector_outcomes)` interface
that returns predicted observable flips.

Simulation runner
-----------------
run_threshold_experiment, run_exhaustive_check

Configuration
-------------
CircuitConfig, DecoderConfig, ThresholdExperimentConfig
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import numpy as np
import stim

from .config import CircuitConfig, DecoderConfig, ThresholdExperimentConfig
from .dem.model import parse_stim_dem, parse_detector_metadata
from .decoder.concat_mwpm import ConcatMatchingDecoder
from .decoder.concat_bp_matching import ConcatBeliefMatchingDecoder
from .runner.experiment import run_threshold_experiment
from .runner.exhaustive_check import run_exhaustive_check


class ConcatMWPMDecoder:
    """Concatenated MWPM decoder — pure graph-based two-stage decoding.

    Decodes color-code circuits by splitting the DEM by color, building
    two-stage hierarchical models, and solving each stage with MWPM.

    Compatible with circuits generated by chromobius or color-code-stim.

    Args:
        circuit: A `stim.Circuit` with detector coordinate annotations encoding
            color and basis information (as produced by chromobius/clorco or
            color-code-stim).
        cfg: Optional decoder configuration. Defaults to `DecoderConfig()`.

    Example::

        import stim
        import concat_decoder

        circuit = stim.Circuit.from_file("my_circuit.stim")
        decoder = concat_decoder.ConcatMWPMDecoder(circuit)

        sampler = circuit.compile_detector_sampler()
        det_outcomes, obs_true = sampler.sample(shots=1000, separate_observables=True)

        obs_pred = decoder.decode_batch(det_outcomes)
        errors = (obs_pred != obs_true).any(axis=1)
        print(f"Logical error rate: {errors.mean():.4f}")
    """

    def __init__(self, circuit: stim.Circuit, cfg: DecoderConfig | None = None):
        if cfg is None:
            cfg = DecoderConfig()
        dem = circuit.detector_error_model(decompose_errors=False)
        base_model = parse_stim_dem(dem)
        metadata = parse_detector_metadata(circuit)
        self._decoder = ConcatMatchingDecoder(
            base_model,
            metadata.detector_ids_by_color,
            cfg,
            detector_basis_by_id=metadata.detector_basis,
        )

    def decode_batch(self, detector_outcomes: np.ndarray) -> np.ndarray:
        """Decode a batch of detector outcomes.

        Args:
            detector_outcomes: Boolean/uint8 array of shape ``(shots, num_detectors)``
                or ``(num_detectors,)`` for a single shot.

        Returns:
            uint8 array of shape ``(shots, num_observables)`` with predicted
            observable flips (0 or 1).
        """
        result = self._decoder.decode_batch(detector_outcomes)
        return np.asarray(result.obs_prediction, dtype=np.uint8)


class ConcatBPMatchingDecoder:
    """Concatenated BP→MWPM hybrid decoder.

    Runs belief propagation (relay-BP) for stage 1 decoding. When BP converges,
    its hard decision is projected to the Z-basis graph. When BP fails to converge,
    its posterior beliefs are marginalized onto the Z-graph as soft weights, then
    MWPM is used as a fallback. Stage 2 always uses MWPM.

    Compatible with circuits generated by chromobius or color-code-stim.

    Args:
        circuit: A `stim.Circuit` with detector coordinate annotations encoding
            color and basis information.
        cfg: Optional decoder configuration. Defaults to `DecoderConfig()`.

    Example::

        import stim
        import concat_decoder

        circuit = stim.Circuit.from_file("my_circuit.stim")
        decoder = concat_decoder.ConcatBPMatchingDecoder(circuit)

        sampler = circuit.compile_detector_sampler()
        det_outcomes, obs_true = sampler.sample(shots=1000, separate_observables=True)

        obs_pred = decoder.decode_batch(det_outcomes)
        errors = (obs_pred != obs_true).any(axis=1)
        print(f"Logical error rate: {errors.mean():.4f}")
    """

    def __init__(self, circuit: stim.Circuit, cfg: DecoderConfig | None = None):
        if cfg is None:
            cfg = DecoderConfig()
        dem = circuit.detector_error_model(decompose_errors=False)
        base_model = parse_stim_dem(dem)
        metadata = parse_detector_metadata(circuit)
        self._decoder = ConcatBeliefMatchingDecoder(
            base_model,
            metadata.detector_ids_by_color,
            cfg,
            detector_basis_by_id=metadata.detector_basis,
        )

    def decode_batch(self, detector_outcomes: np.ndarray) -> np.ndarray:
        """Decode a batch of detector outcomes.

        Args:
            detector_outcomes: Boolean/uint8 array of shape ``(shots, num_detectors)``
                or ``(num_detectors,)`` for a single shot.

        Returns:
            uint8 array of shape ``(shots, num_observables)`` with predicted
            observable flips (0 or 1).
        """
        result = self._decoder.decode_batch(detector_outcomes)
        return np.asarray(result.obs_prediction, dtype=np.uint8)


__all__ = [
    # Public decoders
    "ConcatMWPMDecoder",
    "ConcatBPMatchingDecoder",
    # Configuration
    "CircuitConfig",
    "DecoderConfig",
    "ThresholdExperimentConfig",
    # Simulation runner
    "run_threshold_experiment",
    "run_exhaustive_check",
]
